### ISSUE TITLE
Fix flaky reports' property test

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1602]
This test sometimes fails, here is the output:

```
Failed   Toggl.Foundation.Tests.MvvmCross.ViewModels.ReportsViewModelTests+ThePrepareMethod.FiresACallToLoadReports
Error Message:
 FsCheck.Xunit.PropertyFailedException : 
Falsifiable, after 1 test (3 shrinks) (StdGen (1519295987,296418883)):
Original:
2/11/42 12:46:38 AM -09:16
Shrunk:
2/11/42 12:00:00 AM +00:00
---- NSubstitute.Exceptions.ReceivedCallsException : Expected to receive a call matching:
	GetProjectSummary(10, 2/9/42 12:00:00 AM -08:00, 2/15/42 12:00:00 AM -07:00)
Actually received no matching calls.
Received 4 non-matching calls (non-matching arguments indicated with '*' characters):
	GetProjectSummary(10, 2/9/42 12:00:00 AM -08:00, *2/15/42 12:00:00 AM -08:00*)
	GetProjectSummary(10, 2/9/42 12:00:00 AM -08:00, *2/15/42 12:00:00 AM -08:00*)
	GetProjectSummary(10, 2/9/42 12:00:00 AM -08:00, *2/15/42 12:00:00 AM -08:00*)
	GetProjectSummary(10, 2/9/42 12:00:00 AM -08:00, *2/15/42 12:00:00 AM -08:00*)
Stack Trace:
----- Inner Stack Trace -----
   at NSubstitute.Core.ReceivedCallsExceptionThrower.Throw(ICallSpecification callSpecification, IEnumerable`1 matchingCalls, IEnumerable`1 nonMatchingCalls, Quantity requiredQuantity)
   at NSubstitute.Routing.Handlers.CheckReceivedCallsHandler.Handle(ICall call)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at NSubstitute.Routing.Route.Handle(ICall call)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IReportsProviderProxy.GetProjectSummary(Int64 workspaceId, DateTimeOffset startDate, Nullable`1 endDate)
   at Toggl.Foundation.Tests.MvvmCross.ViewModels.ReportsViewModelTests.ThePrepareMethod.FiresACallToLoadReports(DateTimeOffset now) in /Users/vagrant/git/Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FsCheck.Runner.invokeAndThrowInner@318-1.Invoke(Object[] o)
   at <StartupCode$FSharp-Core>.$Reflect.Invoke@835-4.Invoke(T1 inp)
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a)
```

**Comment by simonrozsival** [comment]
I think this is so outdated now that we can close it. We don't have the test which caused problems anymore and there is afaik no flaky test related to reports (or any flaky test at all at the moment).
