### ISSUE TITLE
Fix flaky test for MainViewModel

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1640]
This test occasionally fails:
```
Failed   Toggl.Foundation.Tests.MvvmCross.ViewModels.MainViewModelTests+TheShouldShowWelcomeBackProperty.ReturnsFalseWhenThereAreSomeTimeEntries
Error Message:
 Expected False, but found True.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions.BeFalse(String because, Object[] becauseArgs)
   at Toggl.Foundation.Tests.MvvmCross.ViewModels.MainViewModelTests.TheShouldShowWelcomeBackProperty.<ReturnsFalseWhenThereAreSomeTimeEntries>d__2.MoveNext() in /Users/vagrant/git/Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs:line 639
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by simonrozsival** [comment]
Another similar failing test I got today which might be related:
```
Failed   Toggl.Foundation.Tests.MvvmCross.ViewModels.MainViewModelTests+TheShouldShowWelcomeBackProperty.ReturnsFalseWhenThereAreSomeSuggestions
Error Message:
 Expected False, but found True.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions.BeFalse(String because, Object[] becauseArgs)
   at Toggl.Foundation.Tests.MvvmCross.ViewModels.MainViewModelTests.TheShouldShowWelcomeBackProperty.<ReturnsFalseWhenThereAreSomeSuggestions>d__1.MoveNext() in /Users/simonrozsival/Projects/github/toggl/mobileapp/Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs:line 630
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
