### ISSUE TITLE
Android beta crash report

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#2563]
Phone:
Xiaomi Mi A1, Android 8.0.0.

Steps:
1. Update Toggl beta to v0.5.
2. Run Toggl.

Result:
Consistent crash on start every time I run Toggl. I see the following error in Logcat:

```
06-28 13:47:20.011 5947-5947/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.toggl.giskard, PID: 5947
android.runtime.JavaProxyThrowable: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException () [0x0000c] in :0
at Toggl.Giskard.Adapters.SegmentedRecyclerAdapter`2[TCollection,TItem].tryGetItem (System.Int32 viewPosition) [0x000a4] in <8458edcb3853431ab1dc5593567ef8b5>:0
at Toggl.Giskard.Adapters.SegmentedRecyclerAdapter`2[TCollection,TItem].GetItem (System.Int32 viewPosition) [0x00017] in <8458edcb3853431ab1dc5593567ef8b5>:0
at Toggl.Giskard.Adapters.MainRecyclerAdapter.GetItem (System.Int32 viewPosition) [0x0003f] in <8458edcb3853431ab1dc5593567ef8b5>:0
at MvvmCross.Droid.Support.V7.RecyclerView.MvxRecyclerAdapter.OnBindViewHolder (Android.Support.V7.Widget.RecyclerView+ViewHolder holder, System.Int32 position) [0x00000] in <3340be3df28b42399a0eb467a1e5a4e8>:0
at Toggl.Giskard.Adapters.MainRecyclerAdapter.OnBindViewHolder (Android.Support.V7.Widget.RecyclerView+ViewHolder holder, System.Int32 position) [0x00001] in <8458edcb3853431ab1dc5593567ef8b5>:0
at Android.Support.V7.Widget.RecyclerView+Adapter.n_OnBindViewHolder_Landroid_support_v7_widget_RecyclerView_ViewHolder_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_holder, System.Int32 position) [0x0000f] in <1c3b474ba0bc45cba6ec33f4b4b4b99a>:0
at (wrapper dynamic-method) System.Object.1a3d0e1f-c7b5-43e2-94d9-466144d1abd0(intptr,intptr,intptr,int)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in :0
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <66d9fb778a5d4b65810d3ab62bada294>:0
at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00015] in :0
at Android.Support.V7.Widget.RecyclerView+LayoutManager.OnLayoutChildren (Android.Support.V7.Widget.RecyclerView+Recycler recycler, Android.Support.V7.Widget.RecyclerView+State state) [0x0009b] in <1c3b474ba0bc45cba6ec33f4b4b4b99a>:0
at MvvmCross.Droid.Support.V7.RecyclerView.MvxGuardedLinearLayoutManager.OnLayoutChildren (Android.Support.V7.Widget.RecyclerView+Recycler recycler, Android.Support.V7.Widget.RecyclerView+State state) [0x00000] in <3340be3df28b42399a0eb467a1e5a4e8>:0
at Android.Support.V7.Widget.RecyclerView+LayoutManager.n_OnLayoutChildren_Landroid_support_v7_widget_RecyclerView_Recycler_Landroid_support_v7_widget_RecyclerView_State_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_recycler, System.IntPtr native_state) [0x00017] in <1c3b474ba0bc45cba6ec33f4b4b4b99a>:0
at (wrapper dynamic-method) System.Object.2caeb079-17eb-48ce-a27f-20f3acf832b0(intptr,intptr,intptr,intptr)
at mvvmcross.droid.support.v7.recyclerview.MvxGuardedLinearLayoutManager.n_onLayoutChildren(Native Method)
at mvvmcross.droid.support.v7.recyclerview.MvxGuardedLinearLayoutManager.onLayoutChildren(MvxGuardedLinearLayoutManager.java:45)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
at android.view.View.layout(View.java:19590)
at android.view.ViewGroup.layout(ViewGroup.java:6053)
at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:610)
at android.view.View.layout(View.java:19590)
at android.view.ViewGroup.layout(ViewGroup.java:6053)
at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1166)
at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:851)
at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
at android.view.View.layout(View.java:19590)
at android.view.ViewGroup.layout(ViewGroup.java:6053)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:19590)
at android.view.ViewGroup.layout(ViewGroup.java:6053)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
at android.view.View.layout(View.java:19590)
at android.view.ViewGroup.layout(ViewGroup.java:6053)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:19590)
at android.view.ViewGroup.layout(ViewGroup.java:6053)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
at android.view.View.layout(View.java:19590)
at android.view.ViewGroup.layout(ViewGroup.java:6053)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
at android.view.View.layout(View.java:19590)
at android.view.ViewGroup.layout(ViewGroup.java:6053)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2488)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2204)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1390)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6754)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
at android.view.Choreographer.doCallbacks(Choreographer.java:778)
at android.view.Choreographer.doFrame(Choreographer.java:713)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:172)
at android.app.ActivityThread.main(ActivityThread.java:6637)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by kornelijepetak** [comment]
I have strong feeling that this was fixed by 
https://github.com/toggl/mobileapp/pull/2606
