### ISSUE TITLE
Reveal animation crashes

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#2647]
I was running some tests for some reviews and found these two crashes:
1. When starting a new TE from the Start TE view when pressing "Save"
2. When stopping the running TE.

This only happened on my Nexus 5 (Android 23). It doesn't happen on the emulator (Tested on 21 and 26). 
Can anyone else reproduce this? This is listed on AppCenter as well.

The stack trace is similar on both cases:
```
 Java.Lang.RuntimeException: Cannot start this animator on a detached view!
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <39692b35a60a4711afc81a0971e6ef27>:0
   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <3ee799ab40744560830977497ff6c070>:0
   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <3ee799ab40744560830977497ff6c070>:0
   at Android.Views.ViewAnimationUtils.CreateCircularReveal (Android.Views.View view, System.Int32 centerX, System.Int32 centerY, System.Single startRadius, System.Single endRadius) [0x00087] in <a28fed84f3be4c2693401091c4052c1b>:0
   at Toggl.Giskard.Extensions.CircularRevealAnimation.<Start>b__17_0 () [0x00031] in <2ab50e46cedc41c699b3bb43d8e4ca00>:0
   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <a28fed84f3be4c2693401091c4052c1b>:0
   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <a28fed84f3be4c2693401091c4052c1b>:0
   at (wrapper dynamic-method) System.Object.7548be92-c5bd-4a66-ade9-49b81b254cc1(intptr,intptr)
   --- End of managed Java.Lang.RuntimeException stack trace ---
 java.lang.IllegalStateException: Cannot start this animator on a detached view!
 	at android.view.RenderNode.addAnimator(RenderNode.java:812)
 	at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)
 	at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)
 	at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
 	at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:55)
 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by daividssilverio** [comment]
This was merged from carbon into develop.
