### ISSUE TITLE
Giskard Crashes Upon Startup

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/mobileapp#2695]
## 🐛 Bug Report
Users are reporting that Giskard/1.0 is crashing upon tapping to open the app. I've been able to reproduce once on Motorola g6 running clean Android 8.0.0
## Context
So far, majority of users with crash issues are reporting from Android 8.0. Will update issue via comments should any additional users report this

Build/Branch: 1.0
Phone OS: Android 8.0
Phone model: Motorola g6

## Expected behavior
Tapping on the app should open it without issue. 
## To reproduce
Tap on the app to open; shows Toggl logo and takes user to main app screen before crashing and eliciting a crash notice to the user
## Suggestions
N/A; as mentioned before, Support will update this report via comments with any changes in trends across users/devices/Android versions

**Comment by kornelijepetak** [comment]
I can't say this is necessarily related, but this does crash when I run the app on Android 8 device:

```
android.content.res.Resources$NotFoundException: String resource ID #0x7f090012
  at android.content.res.Resources.getText(Resources.java:339)
  at android.content.res.Resources.getString(Resources.java:433)
  at android.content.Context.getString(Context.java:557)
  at android.support.v7.widget.ToolbarWidgetWrapper.setNavigationContentDescription(ToolbarWidgetWrapper.java:625)
  at android.support.v7.widget.ToolbarWidgetWrapper.setDefaultNavigationContentDescription(ToolbarWidgetWrapper.java:200)
  at android.support.v7.widget.ToolbarWidgetWrapper.<init>(ToolbarWidgetWrapper.java:178)
  at android.support.v7.widget.ToolbarWidgetWrapper.<init>(ToolbarWidgetWrapper.java:95)
  at android.support.v7.app.ToolbarActionBar.<init>(ToolbarActionBar.java:68)
  at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:217)
  at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:129)
  at md5a44fea7db10133e9f6bddee3bde9d640.MainActivity.n_onCreate(Native Method)
  at md5a44fea7db10133e9f6bddee3bde9d640.MainActivity.onCreate(MainActivity.java:30)
  at android.app.Activity.performCreate(Activity.java:7036)
  at android.app.Activity.performCreate(Activity.java:7027)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
  at android.app.ActivityThread.-wrap11(Unknown Source:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6753)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

This is the scariest part:
`  at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:129)`

It seems that `SetSupportActionBar(toolbar)` in MainActivity's `OnCreate` does not work properly.
As of now, I am still unable to find out why this is throwing. The Activity is indeed AppCompatActivity and Toolbar instance returned is a v7 toolbar. This is very strange.

**Comment by kornelijepetak** [comment]
Just to maybe add some more info, the resource that has not been found is:
`public const int abc_dialog_material_background = 2131296274;`

**Comment by daividssilverio** [comment]
🤔 I actually got hands on a Moto g6 and couldn't reproduce this on the latest develop. https://github.com/toggl/mobileapp/commit/a10dbee95fd420def783545b70b6488284d70dac.

**Comment by daividssilverio** [comment]
Couldn't reproduce it on 1.0 as well. Can you check if this still happening in 1.2? @kornelijepetak and @TheSoloJake ?

**Comment by TheSoloJake** [comment]
@daividssilverio Can't reproduce anymore in 1.1 (don't have 1.2 as of yet)
