### ISSUE TITLE
App crashes when a new tag is created

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2894]
Android version 1.3 internal

## 💥 Crash Report
I opened the app
-Started a new time entry
-Set the description to Test(number)
-Created a project with the same name as the description e.g (Test3).
-Created a client with the same name
-Created a tag with the same name
=The app crashes.

This occurred 3 times in a row, but is no longer occurring.

### 👥 Impact
3 times in a row immediately then hasn't occurred again, need to reinstall and reattempt
This is currently happening on a HTC U Ultra
Android 7.0
### 📝  Exception & Stack Trace
`Exception type and message`
```cs
Stacktrace
```

**Comment by dshr** [comment]
Managed to reproduce this and it's related to #2884, which means it should be solved once the Rxfactoring is done.

**Comment by daividssilverio** [comment]
Hey @dshr , but where did the crash happen? on the Main log or the start te view?

**Comment by dshr** [comment]
In the start te view, right after clicking "Create tag"

**Comment by daividssilverio** [comment]
I see. It doesn't make much sense to be related to #2884 since creating a new TE doesn't add it directly to the main log (unless it's a manual entry).

**Comment by dshr** [comment]
Hm, true. I got that impression bc of the `ArgumentOutOfRangeException` that I got, but now that you mention it, it's inside a completely different VM.

**Comment by kornelijepetak** [comment]
This happened to me, in almost exact scenario with the following stack trace:

```
java.lang.IllegalArgumentException
at android.os.Parcel.readException(Parcel.java:1688)
at android.os.Parcel.readException(Parcel.java:1637)
at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:5505)
at android.app.Activity.isTopOfTask(Activity.java:5978)
at android.app.Activity.cancelInputsAndStartExitTransition(Activity.java:4267)
at android.app.Activity.startActivityForResult(Activity.java:4244)
at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
at android.app.Activity.startActivity(Activity.java:4518)
at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
at android.view.View.performClick(View.java:5637)
at android.view.View$PerformClick.run(View.java:22429)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

However, to make things worse, this can happen to me on any navigation between views, not only when creating tags. In general, this happens in about 5-10% of navigation attempts. 

However, I am not on 1.3, but on current `develop` (as of this moment).

OP did not post any stack trace, but I am really thinking this could be the one.

**Comment by heytherewill** [comment]
📜
