### ISSUE TITLE
Giskard crashes when all sections in the main log are removed

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3288]
## 💥 Crash Report
This is a follow up to #3137, the issue has been fixed in Daneel already.
When all sections in the main log are removed after syncing, the app crashes with an `IndexOutOfBoundsException`.

### 🔗 Context
Steps to reproduce:

1️⃣ Have multiple time entries for different days and the app synced.
2️⃣ Remove all the time entries from the web (or another device).
3️⃣ Pull to refresh in Giskard.
💥 💀 

### 📝  Exception & Stack Trace

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2c27bfa position=1 id=-1, oldPos=3, pLpos:3 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{d4d913 VFED..... ......I. 0,0-1440,2112 #7f0c00f6 app:id/MainRecyclerView}, adapter:md578ad54d0592e2a278920e8d82bce5b52.MainRecyclerAdapter@d58e885, layout:android.support.v7.widget.LinearLayoutManager@75d770b, context:md5a44fea7db10133e9f6bddee3bde9d640.MainActivity@cb3c5fa
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5447)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5629)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3670)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3434)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1171)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:856)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:875)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by daividssilverio** [comment]
This is fixed in sodium. Close this when #3286 gets merged.

**Comment by heytherewill** [comment]
Na
