### ISSUE TITLE
Investingate randomly failing Ultrawave test

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3477]
All of a sudden workspace deserialization unit test in `Ultrawave` is failing (https://app.bitrise.io/build/d32b8452ac020ba3):
```
[xUnit.net 00:00:03.93]     Toggl.Ultrawave.Tests.Models.WorkspaceTests+TheWorkspaceModel.CanBeDeserialized(validJson: "{\"id\":1234,\"name\":\"Default workspace\",\"admi"..., validObject: Workspace { Admin = True, At = 2017-04-24T12:16:48.0000000+00:00, DefaultCurrency = "USD", DefaultHourlyRate = 0, Id = 1234, ... }) [FAIL]
Failed   Toggl.Ultrawave.Tests.Models.WorkspaceTests+TheWorkspaceModel.CanBeDeserialized(validJson: "{\"id\":1234,\"name\":\"Default workspace\",\"admi"..., validObject: Workspace { Admin = True, At = 2017-04-24T12:16:48.0000000+00:00, DefaultCurrency = "USD", DefaultHourlyRate = 0, Id = 1234, ... })
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at FluentAssertions.Equivalency.SelfReferenceEquivalencyAssertionOptions`1.FluentAssertions.Equivalency.IEquivalencyAssertionOptions.GetEqualityStrategy(Type type) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\SelfReferenceEquivalencyAssertionOptions.cs:line 182
   at FluentAssertions.Equivalency.SelfReferenceEquivalencyAssertionOptions`1.FluentAssertions.Equivalency.IEquivalencyAssertionOptions.GetEqualityStrategy(Type type) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\SelfReferenceEquivalencyAssertionOptions.cs:line 175
   at FluentAssertions.Equivalency.ValueTypeEquivalencyStep.CanHandle(IEquivalencyValidationContext context, IEquivalencyAssertionOptions config) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\ValueTypeEquivalencyStep.cs:line 17
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 83
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 38
   at Toggl.Ultrawave.Tests.SerializationHelper.CanBeDeserialized[T](String validJson, T validObject) in /Users/vagrant/git/Toggl.Ultrawave.Tests/Models/SerializationHelper.cs:line 15
   at Toggl.Ultrawave.Tests.Models.WorkspaceTests.TheWorkspaceModel.CanBeDeserialized(String validJson, Object validObject) in /Users/vagrant/git/Toggl.Ultrawave.Tests/Models/WorkspaceTests.cs:line 44
```

Investigate why it failed and try to make sure it never happens again.

**Comment by heytherewill** [comment]
Is this still flaky? @simonrozsival
