### ISSUE TITLE
Fix flaky "midnight" unit test

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3614]
Stack trace:
```
Failed   Toggl.Foundation.Tests.TimeServiceTests+TheMidnightObservableProperty.SubscriberDoesNotReceiveAnyValueEmittedBeforeItSubscribed
Error Message:
 NUnit.Framework.AssertionException : Expected numberOfEmitedValues to be 2, but found 1.
Stack Trace:
   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\LateBoundTestFramework.cs:line 16
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 225
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Numeric\NumericAssertions.cs:line 50
   at Toggl.Foundation.Tests.TimeServiceTests.TheMidnightObservableProperty.SubscriberDoesNotReceiveAnyValueEmittedBeforeItSubscribed() in /Users/vagrant/git/Toggl.Foundation.Tests/TimeServiceTests.cs:line 134
```

**Comment by heytherewill** [comment]
Is this even flaky anymore?

**Comment by simonrozsival** [comment]
There are no flaky tests right now 👍
