### ISSUE TITLE
Fix flaky "get all projects" integration tests

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4248]
## 🐛 Bug Report
There is an integration test which sometimes passes and sometimes it doesn't:

This is the output when it fails:

```cs
[xUnit.net 00:02:26.34]     Toggl.Ultrawave.Tests.Integration.ProjectsApiTests+TheGetAllMethod.ReturnsAllProjects [FAIL]
Failed   Toggl.Ultrawave.Tests.Integration.ProjectsApiTests+TheGetAllMethod.ReturnsAllProjects
Error Message:
 Expected projects to contain 2 item(s), but found 1.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 225
   at FluentAssertions.Collections.SelfReferencingCollectionAssertions`2.HaveCount(Int32 expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\SelfReferencingCollectionAssertions.cs:line 54
   at Toggl.Ultrawave.Tests.Integration.ProjectsApiTests.TheGetAllMethod.ReturnsAllProjects() in /Users/vagrant/git/Toggl.Ultrawave.Tests.Integration/ProjectsApiTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
```

We need to figure out what causes it and we should fix it. Can this problem cause other tests to fail from time to time? And can this problem occur also in the app in production?

## Context

Build/Branch: `develop`

## Expected behavior

The test always passes.

## To reproduce

Run integration tests many times in a row and it might fail.

## Suggestions
I don't have any suggestions. I can just guess that there might be a problem with replication lag around midnight CET? Or that the creation of the project failed for some reason and we didn't process the response and assumed that it worked?

**Comment by simonrozsival** [comment]
I'm closing this now, because we're not having issues with this endpoint.
