### ISSUE TITLE
The BackendStopsPreviousRunningTimeEntryWhenAnotherRunningTimeEntryIsPushed integration test failed

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4316]
## 🐛 Bug Report

Unit test failed with a weird error message:
```csharp
[xUnit.net 00:06:16.56]     Toggl.Ultrawave.Tests.Integration.TimeEntriesApiTests+TheCreateMethod.BackendStopsPreviousRunningTimeEntryWhenAnotherRunningTimeEntryIsPushed [FAIL]
Failed   Toggl.Ultrawave.Tests.Integration.TimeEntriesApiTests+TheCreateMethod.BackendStopsPreviousRunningTimeEntryWhenAnotherRunningTimeEntryIsPushed
Error Message:
 Expected stoppedFirstTimeEntry.Start.AddSeconds(stoppedFirstTimeEntry.Duration.Value) to be <2019-01-30 08:47:47>, but it was <2019-01-30 08:47:48>.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 225
   at FluentAssertions.Primitives.DateTimeOffsetAssertions.Be(DateTimeOffset expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\DateTimeOffsetAssertions.cs:line 49
   at Toggl.Ultrawave.Tests.Integration.TimeEntriesApiTests.TheCreateMethod.<BackendStopsPreviousRunningTimeEntryWhenAnotherRunningTimeEntryIsPushed>d__6.MoveNext() in /Users/vagrant/git/Toggl.Ultrawave.Tests.Integration/TimeEntriesApiTests.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

## Context
This test normally passes, but this time it didn't.

## Expected behavior
The integration test always passes.

## Suggestions
Could it have something to do with network lag or rounding?

**Comment by simonrozsival** [comment]
We haven't seen this problem lately, I'm closing this because it's not an ongoing issue.
