### ISSUE TITLE
Reports API integration tests fail around midnight CET

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4584]
I noticed that at least over the weekend every test which started at 0:00 CET failed with 2 failing tests:
```csharp
Failed   Toggl.Ultrawave.Tests.Integration.TimeEntriesReportsApiTests.ReturnsTrackedSecondsSumWithZeroBillableForAFreeWorkspace
Error Message:
 Expected 3s, but found default.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 225
   at FluentAssertions.Primitives.SimpleTimeSpanAssertions.Be(TimeSpan expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\SimpleTimeSpanAssertions.cs:line 86
   at Toggl.Ultrawave.Tests.Integration.TimeEntriesReportsApiTests.ReturnsTrackedSecondsSumWithZeroBillableForAFreeWorkspace() in /Users/vagrant/git/Toggl.Ultrawave.Tests.Integration/TimeEntriesReportsApiTests.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
```

``` csharp
Failed   Toggl.Ultrawave.Tests.Integration.TimeEntriesReportsApiTests.ReturnsTrackedBillableSecondsSumsForAPaidWorkspace
Error Message:
 Expected 3s, but found default.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 225
   at FluentAssertions.Primitives.SimpleTimeSpanAssertions.Be(TimeSpan expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\SimpleTimeSpanAssertions.cs:line 86
   at Toggl.Ultrawave.Tests.Integration.TimeEntriesReportsApiTests.ReturnsTrackedBillableSecondsSumsForAPaidWorkspace() in /Users/vagrant/git/Toggl.Ultrawave.Tests.Integration/TimeEntriesReportsApiTests.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
```

- https://app.bitrise.io/build/30a334bbd26cad14
- https://app.bitrise.io/build/4f36999e2d992590
- https://app.bitrise.io/build/684f24c88cc44c23

The tests pass correctly at other times during the day.

**Comment by simonrozsival** [comment]
I have a hypothesis on what is wrong and how to fix it I created a branch with an experiment and scheduled a build on Bitrise at midnight so I'll have some more ideas tomorrow.

**Comment by simonrozsival** [comment]
I selected incorrect trigger 🤦‍♂️ so it ran only unit tests and not the integration tests. I rescheduled the build for tomorrow.

**Comment by simonrozsival** [comment]
My experiment failed and I can't seem to be able to replicate this by changing timezones on my computer to run the code "at midnight" somewhere around the world.
