### ISSUE TITLE
Find out why integration tests are failing

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5150]
Since May 13, our integration test runs in Bitrise are frequently failing. Almost always, 1 random integration test fails with `System.Net.Sockets.SocketException : Operation timed out`. It is unclear to me, if this is a problem in our integration tests, the staging server, or Bitrsise VM.

Here are examples of some stack traces of failed tests:

```cs
[xUnit.net 00:10:34.77]     Toggl.Networking.Tests.Integration.TimeEntriesApiTests+TheGetAllBetweenStartAndEndDatesMethod.FailsWithoutCredentials [FAIL]
Failed   Toggl.Networking.Tests.Integration.TimeEntriesApiTests+TheGetAllBetweenStartAndEndDatesMethod.FailsWithoutCredentials
Error Message:
 Toggl.Networking.Exceptions.OfflineException : Offline mode was detected.
---- System.Net.Http.HttpRequestException : Operation timed out
-------- System.Net.Sockets.SocketException : Operation timed out
Stack Trace:
   at Toggl.Networking.ApiClients.BaseApi.<>c.<sendRequest>b__14_0(HttpRequestException e) in /Users/vagrant/git/Toggl.Networking/ApiClients/BaseApi.cs:line 94
   at System.Reactive.Linq.ObservableImpl.Catch`2._.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Catch.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.Subjects.AsyncSubject`1.GetResult() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\AsyncSubject.cs:line 439
   at Toggl.Networking.Tests.Integration.User.createUser(Email email, Password password) in /Users/vagrant/git/Toggl.Networking.Tests.Integration/Helper/User.cs:line 46
   at Toggl.Networking.Tests.Integration.User.Create() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/Helper/User.cs:line 18
   at Toggl.Networking.Tests.Integration.BaseTests.EndpointTestBase.SetupTestUser() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/BaseTests/EndpointTestBase.cs:line 11
   at Toggl.Networking.Tests.Integration.BaseTests.AuthenticatedEndpointBaseTests`1.FailsWithoutCredentials() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/BaseTests/AuthenticatedEndpointBaseTests.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Toggl.Networking.Network.ApiClient.Send(IRequest request) in /Users/vagrant/git/Toggl.Networking/Network/ApiClient.cs:line 29
   at Toggl.Networking.Tests.Integration.Helper.RetryingApiClient.Send(IRequest request) in /Users/vagrant/git/Toggl.Networking.Tests.Integration/Helper/RetryingApiClient.cs:line 46
   at Toggl.Networking.ApiClients.BaseApi.sendRequestAsync(IRequest request, IEnumerable`1 headers) in /Users/vagrant/git/Toggl.Networking/ApiClients/BaseApi.cs:line 99
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```
```cs
[xUnit.net 00:11:36.48]     Toggl.Networking.Tests.Integration.TimeEntriesApiTests+TheDeleteMethod.FailsWithWrongApiToken [FAIL]
Failed   Toggl.Networking.Tests.Integration.TimeEntriesApiTests+TheDeleteMethod.FailsWithWrongApiToken
Error Message:
 Expected Toggl.Networking.Exceptions.UnauthorizedException, but found (aggregated) Toggl.Networking.Exceptions.OfflineException with message "Offline mode was detected."
     at Toggl.Networking.ApiClients.BaseApi.<>c.<sendRequest>b__14_0(HttpRequestException e) in /Users/vagrant/git/Toggl.Networking/ApiClients/BaseApi.cs:line 94
     at System.Reactive.Linq.ObservableImpl.Catch`2._.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Catch.cs:line 123
  --- End of stack trace from previous location where exception was thrown ---
     at System.Reactive.Subjects.AsyncSubject`1.GetResult() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\AsyncSubject.cs:line 439
     at Toggl.Networking.Tests.Integration.BaseTests.AuthenticatedDeleteEndpointBaseTests`1.<>c__DisplayClass0_0.<<CallEndpointWith>b__0>d.MoveNext() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/BaseTests/AuthenticatedDeleteEndpointBaseTests.cs:line 13
  --- End of stack trace from previous location where exception was thrown ---
     at System.Reactive.Subjects.AsyncSubject`1.GetResult() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\AsyncSubject.cs:line 439
     at Toggl.Networking.Tests.Integration.BaseTests.AuthenticatedEndpointBaseTests`1.<>c__DisplayClass5_0.<<CallingEndpointWith>b__0>d.MoveNext() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/BaseTests/AuthenticatedEndpointBaseTests.cs:line 21
.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 225
   at FluentAssertions.Specialized.AsyncFunctionAssertions.Throw[TException](String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Specialized\AsyncFunctionAssertions.cs:line 55
   at Toggl.Networking.Tests.Integration.BaseTests.AuthenticatedEndpointBaseTests`1.FailsWithWrongApiToken() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/BaseTests/AuthenticatedEndpointBaseTests.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
```
```cs
[xUnit.net 00:09:14.92]     Toggl.Networking.Tests.Integration.TimeEntriesApiTests+TheGetAllMethod.WorksWithApiToken [FAIL]
Failed   Toggl.Networking.Tests.Integration.TimeEntriesApiTests+TheGetAllMethod.WorksWithApiToken
Error Message:
 Toggl.Networking.Exceptions.OfflineException : Offline mode was detected.
---- System.Net.Http.HttpRequestException : Operation timed out
-------- System.Net.Sockets.SocketException : Operation timed out
Stack Trace:
   at Toggl.Networking.ApiClients.BaseApi.<>c.<sendRequest>b__14_0(HttpRequestException e) in /Users/vagrant/git/Toggl.Networking/ApiClients/BaseApi.cs:line 94
   at System.Reactive.Linq.ObservableImpl.Catch`2._.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Catch.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.Subjects.AsyncSubject`1.GetResult() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\AsyncSubject.cs:line 439
   at Toggl.Networking.Tests.Integration.User.createUser(Email email, Password password) in /Users/vagrant/git/Toggl.Networking.Tests.Integration/Helper/User.cs:line 46
   at Toggl.Networking.Tests.Integration.User.Create() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/Helper/User.cs:line 18
   at Toggl.Networking.Tests.Integration.BaseTests.EndpointTestBase.SetupTestUser() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/BaseTests/EndpointTestBase.cs:line 11
   at Toggl.Networking.Tests.Integration.BaseTests.AuthenticatedEndpointBaseTests`1.WorksWithApiToken() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/BaseTests/AuthenticatedEndpointBaseTests.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Toggl.Networking.Network.ApiClient.Send(IRequest request) in /Users/vagrant/git/Toggl.Networking/Network/ApiClient.cs:line 29
   at Toggl.Networking.Tests.Integration.Helper.RetryingApiClient.Send(IRequest request) in /Users/vagrant/git/Toggl.Networking.Tests.Integration/Helper/RetryingApiClient.cs:line 46
   at Toggl.Networking.ApiClients.BaseApi.sendRequestAsync(IRequest request, IEnumerable`1 headers) in /Users/vagrant/git/Toggl.Networking/ApiClients/BaseApi.cs:line 99
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```
```cs
[xUnit.net 00:11:01.56]     Toggl.Networking.Tests.Integration.TimeEntriesApiTests+TheCreateMethod.BackendStopsPreviousRunningTimeEntryWhenAnotherRunningTimeEntryIsPushed [FAIL]
Failed   Toggl.Networking.Tests.Integration.TimeEntriesApiTests+TheCreateMethod.BackendStopsPreviousRunningTimeEntryWhenAnotherRunningTimeEntryIsPushed
Error Message:
 Toggl.Networking.Exceptions.OfflineException : Offline mode was detected.
---- System.Net.Http.HttpRequestException : Operation timed out
-------- System.Net.Sockets.SocketException : Operation timed out
Stack Trace:
   at Toggl.Networking.ApiClients.BaseApi.<>c.<sendRequest>b__14_0(HttpRequestException e) in /Users/vagrant/git/Toggl.Networking/ApiClients/BaseApi.cs:line 94
   at System.Reactive.Linq.ObservableImpl.Catch`2._.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Catch.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.Subjects.AsyncSubject`1.GetResult() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\AsyncSubject.cs:line 439
   at Toggl.Networking.Tests.Integration.User.createUser(Email email, Password password) in /Users/vagrant/git/Toggl.Networking.Tests.Integration/Helper/User.cs:line 46
   at Toggl.Networking.Tests.Integration.User.Create() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/Helper/User.cs:line 18
   at Toggl.Networking.Tests.Integration.BaseTests.EndpointTestBase.SetupTestUser() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/BaseTests/EndpointTestBase.cs:line 11
   at Toggl.Networking.Tests.Integration.TimeEntriesApiTests.TheCreateMethod.BackendStopsPreviousRunningTimeEntryWhenAnotherRunningTimeEntryIsPushed() in /Users/vagrant/git/Toggl.Networking.Tests.Integration/TimeEntriesApiTests.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Toggl.Networking.Network.ApiClient.Send(IRequest request) in /Users/vagrant/git/Toggl.Networking/Network/ApiClient.cs:line 29
   at Toggl.Networking.Tests.Integration.Helper.RetryingApiClient.Send(IRequest request) in /Users/vagrant/git/Toggl.Networking.Tests.Integration/Helper/RetryingApiClient.cs:line 46
   at Toggl.Networking.ApiClients.BaseApi.sendRequestAsync(IRequest request, IEnumerable`1 headers) in /Users/vagrant/git/Toggl.Networking/ApiClients/BaseApi.cs:line 99
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

Success history in Bitrise (only `Tests.Integration.Notify`):
![image](https://user-images.githubusercontent.com/374616/58003678-9060bd00-7ae1-11e9-86ea-1c7d4e163045.png)

**Comment by simonrozsival** [comment]
I spoke to @webervin and he pointed out that they are migrating the staging server from Ubuntu 14.04 to 18.04 which might cause problems. Keep in mind that this is just a hypothesis at this moment.

**Comment by simonrozsival** [comment]
It's hard to say what was the cause of the problem, but the problem is gone and the tests are stable now. It was probably something caused by some bad server configuration or buggy tool, which is now apparently fixed. We certainly did not change anything in our app that would have any effect on the integration tests. I'm closing this now.
