### ISSUE TITLE
JobServiceContext.doDequeueWork(JobServiceContext.java:371)

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6040]
## 💥 Crash Report
This seems to be connected to re-enabling android background sync.

### 👥 Impact
Affected around 0.1% of our users
So far this happened only on **Pixel devices** running **Android 10**. 

### 🔗 Context
Maybe this could be related to enabling background sync - https://github.com/toggl/mobileapp/issues/4298

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/1263678719u/overview

### 📝  Exception & Stack Trace
`com.microsoft.appcenter.crashes.Crashes.saveUncaughtException
Crashes.java, line 970`
```cs
java.lang.RuntimeException: An error occurred while executing doInBackground()
  at android.os.AsyncTask$4.done(AsyncTask.java:399)
  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
  at java.util.concurrent.FutureTask.run(FutureTask.java:271)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:919)
  Caused by: java.lang.SecurityException: Caller no longer running, last stopped +5s170ms because: timed out while starting
    at android.os.Parcel.createException(Parcel.java:2071)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:292)
    at android.app.job.JobParameters.dequeueWork(JobParameters.java:248)
    at android.support.v4.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
    at android.support.v4.app.JobIntentService.dequeueWork(JobIntentService.java:640)
    at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
    at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
    at android.os.AsyncTask$3.call(AsyncTask.java:378)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
    Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:493)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:371)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:169)
	at android.os.Binder.execTransactInternal(Binder.java:1021)

```

**Comment by simonrozsival** [comment]
This could be related to #6039

**Comment by semanticer** [comment]
Might be related to this https://issuetracker.google.com/issues/63622293 
One wild guess is that  we should use some higher random JobId instead of "1" in BackgroundSyncJobSchedulerService

**Comment by semanticer** [comment]
This hack allows us catch, log and ignore the crash: https://stackoverflow.com/a/50750543/509681

**Comment by semanticer** [comment]
So, it looks like this is a bug in google's libraries for 3 years now!  
This PR from other project fixed the issue for them apparently https://github.com/optimizely/android-sdk/pull/193

**Comment by semanticer** [comment]
The problem is also that I have no idea how to reproduce this even though I have Pixel device with android 10 :( So if anyone has some suggestion what should I try to get the crash... 

Another temporary solution might be to disable background sync for Android 10 again

**Comment by heytherewill** [comment]
From the exception this seems to be caused by a timeout. Could we change to sync light/PullTimeEntries and then test to see if the app still crashes?

**Comment by semanticer** [comment]
Closing this - there is a new issue created (#6147) and this one is referenced there.
