### ISSUE TITLE
Calendar improvements: crash when creating a lot of TEs at the same time

### ISSUE THREAD

**Issue by pdrj** [toggl/mobileapp#6399]
## 🐛 Bug Report
When there are many (50 in my testing) TEs created at 'the same' time, calendar view crashes.

## Context

Build/Branch: adhoc build linked by @sofokli1 
Phone OS: Android 6
Phone model: XT1092

## Expected behavior
No crash.

## To reproduce
Keep quickly creating TEs (you can use the web UI). Sync and see if you get a crash.

## Stacktrace
```
10-30 12:24:58.366 11845-11845/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.toggl.giskard.adhoc, PID: 11845
    java.lang.IllegalArgumentException: Layout: -4 < 0
        at android.text.Layout.<init>(Layout.java:196)
        at android.text.StaticLayout.<init>(StaticLayout.java:476)
        at android.text.StaticLayout.<init>(StaticLayout.java:462)
        at toggl.droid.views.CalendarDayView.n_onDraw(Native Method)
        at toggl.droid.views.CalendarDayView.onDraw(CalendarDayView.java:73)
        at android.view.View.draw(View.java:16194)
        at android.view.View.updateDisplayListIfDirty(View.java:15190)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15150)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15150)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
...
        at android.view.View.updateDisplayListIfDirty(View.java:15150)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2627)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2446)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2079)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by daividssilverio** [comment]
Closed by #6411
