### ISSUE TITLE
androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork JobIntentService.java

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6807]
## 💥 Crash Report
This is the most prominent crash in Android 2.8.1 - probably related to PM/background sync. 
We currently don't know how to reproduce this. 

### 👥 Impact
Affected users: ∼ 0.2%
This seems to be exclusively **Android 8.0/8.1** problem

### 🔗 Context
probably relates to our usage of PN. Might be also related to the transition to AndroidX.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/3880814495u/overview
and probably also related to
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/544028429u/overview

### 📝  Exception & Stack Trace
`androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork JobIntentService.java
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +8s505ms because: timed out while starting`
```cs
java.lang.RuntimeException: An error occurred while executing doInBackground()
  at android.os.AsyncTask$3.done(AsyncTask.java:353)
  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
  at java.util.concurrent.FutureTask.run(FutureTask.java:271)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
  at java.lang.Thread.run(Thread.java:764)
  **Caused by: java.lang.SecurityException: Caller no longer running, last stopped +8s505ms because: timed out while starting**
    at android.os.Parcel.readException(Parcel.java:1951)
    at android.os.Parcel.readException(Parcel.java:1897)
    at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
    at android.app.job.JobParameters.dequeueWork(JobParameters.java:196)
    at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
    at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
    at android.os.AsyncTask$2.call(AsyncTask.java:333)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)

Thread 2:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.app.ActivityThread.main(ActivityThread.java:6710)
4   java.lang.reflect.Method.invoke(Method.java:-2)
5   com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
6   com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

Thread 598:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
2   java.lang.Daemons$Daemon.run(Daemons.java:103)
3   java.lang.Thread.run(Thread.java:764)

Thread 599:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
5   java.lang.Daemons$Daemon.run(Daemons.java:103)
6   java.lang.Thread.run(Thread.java:764)

Thread 600:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:297)
2   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:277)
3   java.lang.Daemons$Daemon.run(Daemons.java:103)
4   java.lang.Thread.run(Thread.java:764)

Thread 612:
0   android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java:-2)
1   android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:561)
2   android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
3   android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
4   android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:528)
5   com.google.android.gms.measurement.internal.zzao.zza
6   com.google.android.gms.measurement.internal.zzao.zza
7   com.google.android.gms.measurement.internal.zzeb.zzc
8   com.google.android.gms.measurement.internal.zzda.zza
9   com.google.android.gms.measurement.internal.zzda.zza
10  com.google.android.gms.measurement.internal.zzdc.run
11  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
12  java.util.concurrent.FutureTask.run(FutureTask.java:266)
13  com.google.android.gms.measurement.internal.zzbv.run

Thread 615:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 617:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 619:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 630:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1536)
2   java.lang.Thread.getAllStackTraces(Thread.java:1586)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1083)
4   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1048)
5   com.microsoft.appcenter.crashes.UncaughtExceptionHandler.uncaughtException(UncaughtExceptionHandler.java:20)
6   java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
7   java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
8   java.lang.Thread.dispatchUncaughtException(Thread.java:1953)

Thread 631:
0   com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java:-2)
1   com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:351)
2   com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:283)
3   com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:156)
4   com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:119)
5   com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
6   com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
7   com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
8   com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
9   com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:257)
10  com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:478)
11  com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:140)
12  com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:271)
13  com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
14  com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream
15  com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:227)
16  com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
17  com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:49)
18  android.os.AsyncTask$2.call(AsyncTask.java:333)
19  java.util.concurrent.FutureTask.run(FutureTask.java:266)
20  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
21  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
22  java.lang.Thread.run(Thread.java:764)

Thread 632:
0   java.util.HashMap.resize(HashMap.java:677)
1   java.util.HashMap.putVal(HashMap.java:662)
2   java.util.HashMap.put(HashMap.java:611)
3   java.util.HashSet.add(HashSet.java:219)
4   com.android.org.conscrypt.CertBlacklist.readPublicKeyBlackList(CertBlacklist.java:210)
5   com.android.org.conscrypt.CertBlacklist.getDefault(CertBlacklist.java:55)
6   com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:204)
7   com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:164)
8   com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:158)
9   android.security.net.config.NetworkSecurityTrustManager.<init>(NetworkSecurityTrustManager.java:60)
10  android.security.net.config.NetworkSecurityConfig.getTrustManager(NetworkSecurityConfig.java:114)
11  android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
12  com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:203)
13  com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:592)
14  com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java:-2)
15  com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:351)
16  com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:283)
17  com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:156)
18  com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:119)
19  com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
20  com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
21  com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
22  com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
23  com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:257)
24  com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:478)
25  com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:140)
26  com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:271)
27  com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
28  com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream
29  com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:227)
30  com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
31  com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:49)
32  android.os.AsyncTask$2.call(AsyncTask.java:333)
33  java.util.concurrent.FutureTask.run(FutureTask.java:266)
34  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
35  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
36  java.lang.Thread.run(Thread.java:764)

Thread 633:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 634:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:373)
2   java.lang.Thread.sleep(Thread.java:314)
3   com.qti.tcmclient.DpmTcmClient$TcmReceiver.run(DpmTcmClient.java:118)
4   java.lang.Thread.run(Thread.java:764)

Thread 635:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:103)
2   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
3   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
4   java.lang.Thread.run(Thread.java:764)
```

**Comment by daividssilverio** [comment]
Oh no :/ That doesn't make much sense to me now.

**Comment by daividssilverio** [comment]
I'm out of ideas on this one. Un-assigning myself from the issue.
I have theory that this could be related to something being done by one of our third-party libraries,
maybe `AppCenter` or even `Firebase`, but I cannot confirm that.
 
There's one possible link: It seems that this crash only started appearing after we updated AppCenter to its current version on the repo (2.6.1).

**Comment by daividssilverio** [comment]
@semanticer moved to `To-do` as I don't know where it was before in the prioritized list and I wasn't actually working on this issue after it got closed for the first time.

**Comment by daividssilverio** [comment]
Hey @semanticer @heytherewill .... the crash rates from this issue are increasing. 
We should really try some measures against this crash during the release of 2.12.

So far, I think we should try:
1. Updating AppCenter to the latest version.
2. Downgrading AppCenter to the version before this problem started happening.
3. Replace our `JobIntentServices` with `Workers` and the `WorkManager` which is now available for use with Xamarin.
4. Some other idea you might have.

Summed, the four crashes that represent this issue reported on AppCenter are accounting for the majority of the crashes in 2.10. Affecting, silently in theory, 4.1% of the users.

**Comment by pdrj** [comment]
#7112 seems to have fixed the issue.
