### ISSUE TITLE
RenderNodeAnimator.applyInterpolator: NullPointerException: Attempt to invoke virtual method 'long com.android.internal.util.VirtualRefBasePtr.get()' on a null object reference

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#7076]
## 💥 Crash Report
This looks like a crash in the framework when some animation is running.
Not much clue other than that.

### 👥 Impact
This is an old crash that has started happening on 2.2.1.
On Android 2.10, it has affected 0.13% of our users.

### 🔗 Context
This is crash is old and cryptic.
The only clue is that it seems related to animations. We could check every animation done in the app to see if we are doing something wrong.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/2708975997u/overview

### 📝  Exception & Stack Trace
`Exception type and message`
```cs
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.android.internal.util.VirtualRefBasePtr.get()' on a null object reference
  at android.view.RenderNodeAnimator.applyInterpolator(RenderNodeAnimator.java:168)
  at android.view.RenderNodeAnimator.start(RenderNodeAnimator.java:185)
  at android.animation.Animator.startWithoutPulsing(Animator.java:487)
  at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1142)
  at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1046)
  at android.animation.AnimatorSet.pulseAnimationFrame(AnimatorSet.java:1095)
  at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1163)
  at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1054)
  at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
  at android.animation.AnimationHandler.-wrap2(Unknown Source)
  at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
  at android.view.Choreographer.doCallbacks(Choreographer.java:723)
  at android.view.Choreographer.doFrame(Choreographer.java:655)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
  at android.os.Handler.handleCallback(Handler.java:790)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6626)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by pdrj** [comment]
[Also present in 2.11.1](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/2693524791u/overview).

**Comment by daividssilverio** [comment]
Still present it 2.12. Scheduling this issue to be investigated at 2.14.
This is affecting like 0.3% of the users in 2.11.1 and 0.1% of the users in 2.12.

**Comment by daividssilverio** [comment]
I've looked at our source code and the `RenderNodeAnimator` available source code... and I'm not sure this is a problem caused by something we are doing 🤔 .

Interesting enough, this isn't happening on android >= 9 🤔 ...
We could track an event for each animation we start in the app and maybe then we could figure out which animation, or if something we are doing is causing the crashes, then we could act again.

What do you think @amulware ?

Any other @toggl/androids want to take another look?

**Comment by heytherewill** [comment]
This happened 13 times in the last 30 days. Daivid already tried and failed to figure something out. My vote would be to close it, since changing animation code might simply increase the number of crashes.
